# 1) Imagen base con Python
FROM python:3.10-slim

# 2) Directorio de trabajo
WORKDIR /app

# 3) Copiar sólo requirements y bloquear versiones
COPY proyecto/python/requirements.txt ./

# 4) Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# 5) Copiar el resto de la app
COPY proyecto/python/ ./

# 6) Variables de entorno (puedes parametrizar más con .env)
ENV FLASK_ENV=production \
    AWS_REGION=us-east-1

# 7) Exponer el puerto de Flask
EXPOSE 5000

# 8) Comando de arranque
CMD ["python", "app.py"]
