# Imagen base oficial de Python 3.11 (puedes ajustarla según tu versión de Python)
FROM python:3.11-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios del proyecto al contenedor
COPY requeriments.txt ./

# Instala las dependencias de Python
RUN pip install --no-cache-dir -r requeriments.txt

# Copia el resto de los archivos de la app
COPY app.py ./

# Establece la variable de entorno para evitar que Python genere archivos .pyc
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Expone el puerto 5000 (puerto por defecto de Flask)
EXPOSE 5000

# Comando para ejecutar la aplicación Flask
CMD ["python", "app.py"]
